"""Writes options.js (window.OPT929) from people.py and hearts.py — the one file the render driver and the
HTML sheet both read, so a picture can never show geometry other than the one that would ship."""
import json, os
import people
try:
    import hearts
    HEARTS = hearts.OPTIONS
except ImportError:
    HEARTS = {}
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, 'options.js'), 'w') as f:
    f.write('/* GENERATED by tools/design/929/build.py — #929 option geometry in FM.SHAPE_POLYS format. */\n')
    f.write('window.OPT929 = ' + json.dumps({'people': people.OPTIONS, 'hearts': HEARTS}) + ';\n')
print('wrote options.js')
